version: 2
jobs:
  build:
    working_directory: ~/Tvmaze
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Common Module Unit Tests
          command: ./gradlew common:test
      - store_artifacts:
          path: common/build/reports
          destination: reports
      - store_test_results:
          path: common/build/test-results
      - run:
          name: Run Common Detekt
          command: ./gradlew common:detekt
      - run:
          name: Run FeactureTV Module Unit Tests
          command: ./gradlew feature-tv:test
      - store_artifacts:
          path: feature-tv/build/reports
          destination: reports
      - store_test_results:
          path: feature-tv/build/test-results
      - run:
          name: Run FeactureTV Detekt
          command: ./gradlew feature-tv:detekt