version: 2
jobs:
  feature_tv:
    working_directory: ~/Tvmaze
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Run FeactureTV Module Unit Tests
          command: ./gradlew feature-tv:test
      - store_artifacts:
          path: feature-tv/build/reports
          destination: reports
      - store_test_results:
          path: feature-tv/build/test-results
      - run:
          name: Run FeactureTV Detekt
          command: ./gradlew feature-tv:detekt
  common:
    working_directory: ~/Tvmaze
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Run Common Module Unit Tests
          command: ./gradlew common:test
      - store_artifacts:
          path: common/build/reports
          destination: reports
      - store_test_results:
          path: common/build/test-results
      - run:
          name: Run Common Detekt
          command: ./gradlew common:detekt
workflows:
  version: 2
  build_and_test:
    jobs:
      - feature_tv
      - common